language: cpp

compiler:
  - gcc
  - clang

env:
  -
  - DEBUG=1
  - DEBUG=2
  - DEBUG=3

cache: apt

sudo: false

addons:
  apt:
    packages:
    - g++-4.8-multilib
    - clang-3.6

before_script:
  - export CC="$CC -Werror"
  - export CXX="$CXX -Werror"

script:
  - make -kj DEBUG=$DEBUG

notifications:
  email: false

matrix:
  fast_finish: true
