language: cpp

sudo: false

cache: apt

notifications:
  email: false

_packages:
  - &default_packages
    - time # For build
  - &GCC
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-4.9-multilib
    before_install:
      - export CC="gcc-4.9"
      - export CXX="g++-4.9"
  - &Clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.5
        packages:
          - *default_packages
          - libstdc++-4.9-dev # Proper version of std library
          - clang-3.5
    before_install:
      - export CC="clang-3.5"
      - export CXX="clang++-3.5"

matrix:
  fast_finish: true
  include:
    # GCC
    - compiler: gcc
      <<: *GCC
      env:
    - compiler: gcc
      <<: *GCC
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC
      env: DEBUG=2
    # Clang
    - compiler: clang
      <<: *Clang
      env:
    - compiler: clang
      <<: *Clang
      env: DEBUG=1
    - compiler: clang
      <<: *Clang
      env: DEBUG=2

before_script:
  - $CC -v
  - $CXX -v
  - export CC="$CC -Werror"
  - export CXX="$CXX -Werror"

script:
  - make -kj $(grep -c ^processor /proc/cpuinfo) DEBUG=$DEBUG
  - make -kj $(grep -c ^processor /proc/cpuinfo) DEBUG=$DEBUG test
