language: cpp

compiler:
  - gcc
  - clang

env:
  -
  - DEBUG=1
  - DEBUG=2
  - DEBUG=3

cache: apt

sudo: false

script:
  - make -kj DEBUG=$DEBUG

notifications:
  email: false

matrix:
  fast_finish: true
